os: linux
Language: php
php:
    - 7.1
    - 7.2
    - 7.3
    - 7.4
cache:
    - $HOME/.composer/cache
    - ${TRAVIS_BUILD_DIR}/travis/extension-cache
    - vendor
before_script:
    - travis_retry composer self-update --stable -n
    - travis_retry composer update --no-interaction --prefer-source
script:
    - ./vendor/bin/phpunit
notifications:
    email: false